---
sudo: false
language: ruby
rvm:
  - 2.5.3
script: bundle exec rake test
services:
  - postgresql
  - mysql
addons:
  postgresql: 10
before_install:
  - mysqladmin create set_as_primary_test
  - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
  - createdb set_as_primary_test
notifications:
  email:
    on_success: never
    on_failure: change
