name: build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        include:
          - ruby: 3.0
            gemfile: test/gemfiles/activerecord61.gemfile
          - ruby: 3.1
            gemfile: Gemfile
    runs-on: ubuntu-latest
    env:
      CC_TEST_REPORTER_ID: 353b5634de390dad574939f59c2ef3798b81f06df548f7bdd11cd8225be484f3
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install Bundler
        run: gem install bundler

      - name: Install dependencies
        run: bundle install

      - name: Set up Code Climate Test Reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build

      - uses: ankane/setup-postgres@v1
        with:
          database: set_as_primary_test

      - uses: ankane/setup-mysql@v1
        with:
          database: set_as_primary_test
      - run: mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql

      - name: Run tests
        run: bundle exec rake test

      - name: Upload test coverage results to Code Climate
        if: always() && ${{ github.ref == 'refs/heads/master' }} # Adjust the branch name if needed
        run: ./cc-test-reporter after-build --debug